// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdgetg08vA7rz3cDPs__mSS3OXqIvkb2U',
    appId: '1:603229566932:web:8e21d627f020b5d56a0841',
    messagingSenderId: '603229566932',
    projectId: 'ai-diary-mobilne',
    authDomain: 'ai-diary-mobilne.firebaseapp.com',
    storageBucket: 'ai-diary-mobilne.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwoeQAI31CMemuPnXzyRBxVoaTnsy5J8',
    appId: '1:603229566932:android:155cb699536479b36a0841',
    messagingSenderId: '603229566932',
    projectId: 'ai-diary-mobilne',
    storageBucket: 'ai-diary-mobilne.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfpOfowc2sjPdQo7HlqiT4aq1rvOn6AwM',
    appId: '1:603229566932:ios:0421e6c2ebc991a46a0841',
    messagingSenderId: '603229566932',
    projectId: 'ai-diary-mobilne',
    storageBucket: 'ai-diary-mobilne.firebasestorage.app',
    iosBundleId: 'com.example.aiDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfpOfowc2sjPdQo7HlqiT4aq1rvOn6AwM',
    appId: '1:603229566932:ios:0421e6c2ebc991a46a0841',
    messagingSenderId: '603229566932',
    projectId: 'ai-diary-mobilne',
    storageBucket: 'ai-diary-mobilne.firebasestorage.app',
    iosBundleId: 'com.example.aiDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdgetg08vA7rz3cDPs__mSS3OXqIvkb2U',
    appId: '1:603229566932:web:7efe72c2e90790976a0841',
    messagingSenderId: '603229566932',
    projectId: 'ai-diary-mobilne',
    authDomain: 'ai-diary-mobilne.firebaseapp.com',
    storageBucket: 'ai-diary-mobilne.firebasestorage.app',
  );
}
